name: Build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install meson ninja
      - run: |
          meson setup release --buildtype release
          meson compile -C release
      - uses: actions/upload-artifact@v4
        with:
          path: release/src
